name: hscrtmpl
version: '1.6'
synopsis: Haskell shell script template
description: A template for writing shell scripts in Haskell. Contains some useful functions and examples of things commonly done in bash.
license: ISC
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2018 Dino Morelli
category: Application, Console, Scripting
extra-source-files:
- changelog.md
- README.md
- package.yaml
- stack.yaml

github: dino-/hscrtmpl

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

# Hey! hscrtmpl.hs is a *script*, you don't have to build it unless
# you want to have a binary!
executables:
  hscrtmpl:
    main: hscrtmpl.hs
    dependencies:
      - base
      - directory
      - filepath
      - process
      # - regex-compat
      - time
      # - time-locale-compat
